/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.alcaldia.aseourbano.censo;

public final class R {
  public static final class color {
    public static final int bg_dark=0x7f010000;
  }
  public static final class string {
    public static final int app_name=0x7f020000;
  }
}